- pkg/spdk/engine.go
```
instance-manager-1494adfe8b78d0600225cc3d15923e00:/ # ./spdk/scripts/rpc.py nvmf_get_subsystems
[
{
"nqn": "nqn.2014-08.org.nvmexpress.discovery",
"subtype": "Discovery",
"listen_addresses": [],
"allow_any_host": true,
"hosts": []
},
{
"nqn": "nqn.2023-01.io.longhorn.spdk:pvc-275f46df-7f12-408e-aedf-a434a53b27a3-e-927bd756",
"subtype": "NVMe",
"listen_addresses": [
{
"transport": "TCP",
"trtype": "TCP",
"adrfam": "IPv4",
"traddr": "10.42.1.30",
"trsvcid": "20002"
}
],
...
```
> Compare network protocol strings regardless of the case

- pkg/spdk/replica.go
If a volume is detached and its replicas are stopped, the replica state will be set to "error" after restarting instance-manager pods.
> Fix wrong replica state

- go.mod
- go.sum
- pkg/spdk/client.go
- pkg/spdk/disk.go
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/util/util.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/jsonrpc/types.go
- vendor/modules.txt
- Mark non-stopped and non-error replicas and engines as error when spdk_tgt is down 
When the spdk_tgt is somehow down, the replicas and engines are out of sync, need to mark non-stopped and non-error replicas and engines as error. Then, longhorn-manager can be aware of the failed replicas and engines and clean them up.
- Restart spdk_tgt and reconnect to it if it is somehow down
longhorn/longhorn#6071
longhorn/longhorn#6155
> Improve resilience to spdk_tgt crash

- pkg/spdk/server.go
After receiving a shutdown singal, the spdk gRPC server should stop.
Longhorn/longhorn#7263
> Add shutdown channel

- pkg/spdk/engine.go
In some failed cases, SPDK engine raises an error `nvmf ... subsystem already exists` while attempting to create a new subsystem for a RAID bdev. This is due to orphaned resources remaining undeleted after encountering an error.
To prevent this error message, we can blindly stop raid bdev exposure for cleaning up the orphaned resources before exposing it.
longhorn/longhorn#7324
> Blindly stop raid bdev exposure before exposing it

- go.mod
- go.sum
- pkg/spdk/replica.go
- pkg/spdk/restore.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go
- vendor/modules.txt
Issue longhorn/longhorn#7577
Correct the naming of v2 volume snapshot created after backup restoration.
The wrong naming of snapshots leads to the unexpected snapshot deletion.
> Correct the naming of v2 volume snapshot created after backup restoration.

- pkg/spdk/replica.go
Issue Longhorn/longhorn#7575
When deleting a snapshot lvol, the merge of lvols results in a change of actual size. The error make a replica be marked as error. Do not return error to prevent a false alarm.
> Prevent the false alarm caused by the check of actual size

- go.mod
- go.sum
- pkg/spdk/backup.go
- pkg/spdk/engine.go
- pkg/spdk/restore.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/util/dmsetup.go
- vendor/modules.txt
Issue longhorn/longhorn#7579
Skip validation if dm device is busy and broken to avoid the attaching/detaching loop of a volume using by a Pod (without a controller).
Deps on https://github.com/longhorn/go-spdk-helper/pull/69
> Skip validation if dm device is busy and broken

- pkg/spdk/replica.go
Issue Longhorn/longhorn#7630
Allow to clean up volume-head when reverting to the parent of the volume-head.
Make the behavior of v1 and v2 volume consistent.
> Allow to clean up volume-head when reverting to the parent of the volume-head

- go.mod
- go.sum
- pkg/spdk/backup.go
- pkg/spdk/engine.go
- pkg/spdk/restore.go
- pkg/spdk/server.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/nvme.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
- vendor/modules.txt
Issue https://github.com/longhorn/longhorn/issues/7697
- Allow derferred dm device deletion accordingly
When deleting a replica, no need to delete a dm device by a blocking method.
- Pass DefaultKeepAliveTimeoutMs to BdevNvmeSetOptions
Deps on https://github.com/longhorn/go-spdk-helper/pull/70
> Updates for dm deferred deletion option and the ctrl-loss-tmo of "nvme connect"

- pkg/spdk/engine.go
- pkg/spdk/replica.go
After rebuilding failed, the previous rebuilding info in the source replica won't be cleaned up. Then the following rebuilding cannot use that source replica anymore.
Issue https://github.com/longhorn/longhorn/issues/7723
> spdk: Blindly finish rebuilding for src replica after rebuilding failure

- pkg/spdk/server.go
Protect spdkClient in ReplicaCreate when replacing the client when there is a connection issue.
Issue Longhorn/longhorn#7752
> Protect spdkClient in ReplicaCreate

- go.mod
- go.sum
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk/types.go
- pkg/spdk/util.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/advanced.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
- vendor/modules.txt
Issue Longhorn/longhorn#8551
Expose local logical volumes and attach them to the local node
1. Expose local logical volumes and attach them to the local node
2. To expose a logical volume and attach it to the local node, NGUID should be provided.
>  Expose local logical volumes and attach them to the local node

- pkg/spdk/engine.go
Issue Longhorn/longhorn#6001
Function name getBdevNameForReplica is misleading.
> Replace getBdevNameForReplica with connectReplica

- pkg/api/types.go
- pkg/client/client.go
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk_test.go
Issue #7641
I added the timestamp only to the snapshots created by the user, because they are the only ones listed in the UI.
> engine: add timestamp to user created snapshot

- Dockerfile.dapper
- go.mod
- go.sum
- vendor/modules.txt
> chore(dockerfile): update spdk to a6478cd

- pkg/spdk/engine.go
Issue #8862
The snapshot creation time is now in the right `RFC3339` format
> fix(engine): correct format for snapshot timestamp

- pkg/spdk/engine.go
Issue Longhorn/longhorn#8977
The commit (da2a02e) results in a regression that v2 volume data are not sync before taking a snapshot. Using sync directly with a block device path does not work as expected.
According to the doc of the sync command, what it does is to synchronize the filesystem which contains the specified file.
> fix(snapshot): revert "engine: sync only own device before snapshot"

- go.mod
- go.sum
- pkg/spdk/replica.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
- vendor/modules.txt
Set user_created to true when the xattr isn´t available to let the UI to show the snapshots list.
Issue #9054
> fix(deps): update go-spdk-helper for user_created fallback

- pkg/client/client.go
- pkg/spdk/disk.go
- pkg/spdk/disk/nvme/nvme.go
- pkg/spdk/disk/virtio-blk/virtio-blk.go
- pkg/spdk/disk/virtio-scsi/virtio-scsi.go
Issue Longhorn/longhorn#9126
- If disk UUID is not provided while deleting a disk. Use disk name instead.
- Unbind a disk if failed to attach it while attaching.
> fix(disk): unable to unbind disk if it is failed to create it

- pkg/spdk/engine.go
Issue Longhorn/longhorn#9190
If the bdev name in ReplicaBdevNameMap is missing, BdevRaidRemoveBaseBdev has no chances to delete the base bdev.
> fix: no need to empty bdev name in ReplicaBdevNameMap

- pkg/spdk/engine.go
> refactor: engine consolidates the replica related maps into a single one

- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk/types.go
Considering there may be broken replicas reusage, w need a better way to handle replica head and snap chain
> refactor: refactor replica head and snap chain related implementation

- Dockerfile.dapper
Longhorn 9700
Issue https://github.com/longhorn/longhorn/issues/9700
> fix(deps): update Dockerfile to SPDK longhorn-v24.09 branch

- pkg/client/client.go
> fix: fix potential nil dereference error

- go.mod
- go.sum
- pkg/client/types.go
- pkg/spdk/backup.go
- pkg/spdk/disk.go
- pkg/spdk/disk/nvme/nvme.go
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/restore.go
- pkg/spdk/server.go
- pkg/spdk/types.go
- pkg/spdk/util.go
- pkg/util/block.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
- vendor/modules.txt
Issue Longhorn/longhorn#9874
Signed-off-by: Derek Su <derek.su@suse.com>
> fix: decrease ctrlr_loss_timeout_sec for base bdev 

- pkg/spdk/engine.go
Issue longhorn/longhorn#9852
Fix NPE error.
`None`
`None`
> fix: NPE error

- go.mod
- go.sum
- pkg/spdk/disk/nvme/nvme.go
- pkg/spdk/types.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
- vendor/modules.txt
Issue Longhorn/longhorn#9874
Signed-off-by: Derek Su <derek.su@suse.com>
> feat: decrease transport_ack_timeout

- go.mod
- go.sum
- pkg/client/client.go
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk_test.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/advanced.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
- vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go
- vendor/modules.txt
Issue Longhorn/longhorn#9919
Signed-off-by: Derek Su <derek.su@suse.com>
> refactor: mainly refactor engine codes

- pkg/spdk/backup.go
ref: https://github.com/longhorn/longhorn/issues/10013
Always return 0 if lvolName is not provided
Note that, 0 can be a BackingImage is ActiveChain[0] != nil
Caller need to handle this case.
> fix: always return 0 index if lvol is not provided when finding index

- pkg/spdk/replica.go
- pkg/spdk/server.go
Issue Longhorn/longhorn#10033
If the replica's ActiveChain is not constructed while creating the replica, the mismatch found by the `validateAndUpdate()` will result in the error state.
```
....
newSnapshotLvolMap, err := constructSnapshotLvolMap(r.Name, bdevLvolMap)
if err != nil {
return err
}
if len(r.SnapshotLvolMap) != len(newSnapshotLvolMap) {
return fmt.Errorf("replica current active snapshot ....")
}
...
````
> fix: reconstruct ActiveChain and SnapshotLvolMap while creating replica

- pkg/spdk/server.go
- pkg/spdk_test.go
- pkg/util/http_handler.go
- scripts/test
Issue Longhorn/longhorn#9953
- fix(server): add replica to replicaMap after replica creation and initialization
- fix race conditions in spdk_tgt.go
- fix(scripts): prevent different test suites from running concurrently
- fix(backingimage): increase HTTPTimeout to 10 seconds
> fix(server): fix race conditions

- pkg/spdk/replica.go
Issue longhorn/longhorn#9488
If the upper layer tries to launch a previously failed replica in a newly launched instance manager pod. The pod may have no info then directly treat it as a new replica and skip the cache reconstruction. Finally, this replica will be failed by r.validateAndUpdate() in the next moment.
> fix: reconstruct the cache for failed replica restarting

- pkg/spdk/replica.go
Issue Longhorn/longhorn#10116
Reproduce steps:
1. Create a v2 volume
2. Take one snapshot
3. Delete the v2 volume
4. Go the instance-manager pod and check the orphaned lvols by `go-spdk-lvol lvol get`
> fix: delete lvol with empty base snapshot

- pkg/spdk/engine.go
Issue Longhorn/longhorn#10139
Bdev names of replicas are empty while creating a raid bdev after finishing backup restore.
> fix: bdev names of replicas are empty while creating a raid bdev

- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
Issue Longhorn/longhorn#10136
Replica address is missing in the backup status response. The replica address is required for test_basic.py::test_backup_status_for_unavailable_replicas.
> fix: replica address is missing in the backup status response

- pkg/spdk/backing_image.go
- pkg/util/http_handler.go
ref: https://github.com/longhorn/longhorn/issues/9876
Since @derekbit has fixed the issue of spdk lvol init doesn't clean up the old data 
We can now skip writing the data when dumping backing image data to lvol
> fix: skip write zero when dumping backing image data to lvol

- pkg/spdk/engine.go
- pkg/spdk/replica.go
> fix: engine skips dst replica during rebuilding finish if it is already removed

- pkg/spdk/backing_image.go
- pkg/spdk/server.go
ref: [longhorn/longhorn 10342](https://github.com/longhorn/longhorn/issues/10342)
Since we skip writing zero into the lvol when creating v2 backing image
the size of the backing image should be `bdevLvol.NumBlocks * uint64(bdevLvol.BlockSize)` instead of using `NumAllocatedClusters`
For example, parrot is 32 MB but it only allocates 6 clusters
We should report 32MB when getting the backing image size.
> fix: fix backing image size calculation

- pkg/spdk/backing_image.go
- pkg/spdk/server.go
- pkg/types/types.go
ref: https://github.com/longhorn/longhorn/issues/10399
change the attr key name used by backing image
we should add a longhorn prefix to the preserved attr name in spdk
> fix: fix v2 snapshot attribute key name checksum conflict

- scripts/test
Issue Longhorn/longhorn#10684
During CI testing, spdk_tgt is repeatedly started and stopped. To prevent interference between concurrent CI tasks, only one SPDK CI test is allowed at a time by using a file lock.
> test: only one SPDK CI test is allowed at a time by using a file lock

- pkg/spdk/engine.go
Issue https://github.com/longhorn/longhorn/issues/9023
> feat(engine): suspend and flush IO before snapshot

- pkg/spdk_test.go
Issue #
concurrentCount to 10 takes 3-4 hours to complete. To reduce the CI test time, change the concurrentCount to 5.
> test: reduce the concurrentCount to 5

- Dockerfile.dapper
Issue #
SPDK ublk needs liburing2.
- amd64 liburing-devel is already liburing2.
- arm64 needs to install liburing2-devel explicitly.
ref: https://github.com/spdk/spdk/issues/3282
> chore(Dockerfile): fix arm64 build failed

- pkg/api/types.go
- pkg/spdk/engine.go
- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk/types.go
- pkg/types/types.go
Issue Longhorn/longhorn#10526
The parent field of a backing image returned to the instance manager should be empty.
> fix: parent field of a backing image returned to the instance manager should be empty

- pkg/spdk/replica.go
- pkg/spdk/server.go
- pkg/spdk/types.go
Issue
https://github.com/longhorn/longhorn/issues/10828
https://github.com/longhorn/longhorn/issues/11188
> fix: server should scan possible existing replicas when adding a new disk

- pkg/spdk/disk/types.go
- pkg/spdk/disk/types_test.go
Issue Longhorn/longhorn#11127
uio_pci_generic and vfio_pci are uio-pci-generic and vfio-pci on some OS like talos.
> fix: handle the naming variant of uio_pci_generic and vfio_pci

- pkg/spdk/backup.go
Issue longhorn/longhorn#11461
Previously, attempting to back up an older snapshot after a new snapshot was backed up would fail with `invalid snapshot lvol range` because the comparing snapshot was not a valid ancestor.
With this change, the backup falls back to a full backup when the comparing snapshot is not an ancestor, ensuring that older snapshots can be backed up reliably.
`None`
`None`
> fix(backup): fallback to full backup if comparing snapshot is not an ancestor
