README.md

Signed-off-by: Sheng Yang <sheng@yasker.org>

Update README.md with Longhorn org - part 2

---

go.mod
go.sum
pkg/spdk/engine.go
vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvme.go
vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go
vendor/modules.txt

The error is recoverable and no need to mark the engine as error.
waiting for https://github.com/longhorn/go-spdk-helper/pull/37
Longhorn/longhorn#5744

Ignore error due to controller's connecting or resetting state

---

pkg/spdk/client.go
pkg/spdk/disk.go
pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/server.go

Waiting for https://github.com/longhorn/longhorn-spdk-engine/pulls
Longhorn/longhorn#6067
Longhorn/longhorn#6071

 Protect SPDK client by a mutex lock

---

go.mod
go.sum
pkg/spdk/client.go
pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/server.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/nvme.go
vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
vendor/modules.txt

Waiting for https://github.com/longhorn/go-spdk-helper/pull/38
longhorn/longhorn#6110

Set transport_ack_timeout for recognizing TCP disconnection

---

go.mod
go.sum
vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/nvmecli.go
vendor/modules.txt

vendor: update go-spdk-helper

---

pkg/client/client.go
pkg/spdk/server.go

Set ClientConn to nil after closing it

---

pkg/spdk/disk.go

disk service: check lvstore existence before creating a new one

---

pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/types.go

https://github.com/longhorn/longhorn/issues/6341

Reserve Replica.ActiveChain[0] for backing image

---

pkg/client/client.go

https://github.com/longhorn/longhorn/issues/7291

refactor: replace deprecated grpc.WithInsecure

---

.drone.yml
.gitignore
Dockerfile.dapper
pkg/client/client.go
scripts/build
scripts/ci

context: https://github.com/longhorn/longhorn-spdk-engine/pull/64#issuecomment-1855237283

build: fix python dep issue for gRPC update

---

Dockerfile.dapper

uuid-devel for arm64 is not found.

chore(ci): install libuuid-devel rather than uuid-devel

---

Dockerfile.dapper
scripts/validate

https://github.com/longhorn/longhorn/issues/7366

ci: add condition for merge to master

---

pkg/util/util.go

Fix errors found static check

---

pkg/spdk/engine.go
pkg/spdk/replica.go

Do not clean up error message if instance is in error state

---

pkg/spdk/server.go

Issue longhorn/longhorn#7551
A liveness probe will be introduced for detecting the spdk_tgt. If spdk_tgt is crashed, instance-manager pod will be restarted.

No need to restart spdk_tgt if it is crashed

---

pkg/spdk/replica.go

Issue longhorn/longhorn#7583
The inability to delete a replica during restoration isn't an actual error condition. Therefore, there's no necessity to flag it as an error in the state.

Prevent error state sssignment for unsuccessful replica deletion during restoration

---

pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk_test.go

spdk: Engine show the correct snapshot and head info

---

pkg/spdk/engine.go
pkg/spdk_test.go

Issue https://github.com/longhorn/longhorn/issues/7573

spdk: Prohibit deleting a snapshot containing multiple children or child volume-head

---

pkg/spdk/replica.go

Related to https://github.com/longhorn/longhorn/issues/7573#issuecomment-1895640127 but this PR cannot fix it
When [this error](https://github.com/longhorn/longhorn/issues/7573#issuecomment-1895640127) is triggered and the replica becomes failed during detaching, the **replica cannot be updated to state `stopped`** hence **the volume gets stuck in detaching state**

spdk: Make sure an errored replica can be stopped or terminated

---

pkg/spdk_test.go

test: fix test cases due to the change of namespaced Execute()

---

Dockerfile.dapper

Dockerfile: update spdk to 62a8f8a

---

pkg/spdk/replica.go
scripts/validate

https://github.com/longhorn/longhorn/issues/7448

fix: golangci-lint error

---

pkg/client/client.go

fix(lint): replace grpc Dial with NewClient

---

.github/workflows/build.yml
Dockerfile.dapper
pkg/spdk_test.go
scripts/ci
scripts/test

https://github.com/longhorn/longhorn/issues/8039

ci: change to use GitHub actions

---

Dockerfile.dapper
pkg/spdk_test.go
scripts/test

Issue #
This reverts commit fcc8c7aac161eb8950029724d6b948ffee213c4e.
Revert the WIP and test codes.

Revert "WIP"

---

Dockerfile.dapper
pkg/spdk_test.go
scripts/test

ci: simplify spdk_tgt start and stop

---

pkg/spdk/engine.go
pkg/spdk/server.go

Issue longhorn/longhorn#7578
This is the last development about snapshot user create flag

engine: add UserCreated flag to SnapshotCreate

---

.gitignore

chore(gitignore): ignore coverage.out

---

scripts/test

Signed-off-by: Derek Su <derek.su@suse.com>
Issue #

chore(test): do not print spdk_tgt log messages in the foreground

---

scripts/test

chore(test): remove redundant lines

---

Dockerfile.dapper

chore(deps): update nvme-cli and spdk

---

Dockerfile.dapper

chore(dockerfile): use python311 for preventing dependency errors

---

pkg/spdk/replica.go

fix(replica): missing timestamp and userCreated for SnapshotCreate()

---

go.mod
go.sum
pkg/spdk/backup.go
pkg/spdk/restore.go
vendor/github.com/longhorn/go-spdk-helper/pkg/nvme/initiator.go
vendor/modules.txt

fix(backup/restore): clean up endpoint after backup and restore 

---

pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/util.go
pkg/spdk_test.go

fix: fix bugs for rebuilding and snapshot purge then add more test steps

---

pkg/spdk/replica.go
pkg/spdk/server.go
pkg/spdk/types.go

Issue 
longhorn/longhorn#7199
longhorn/longhorn#9121

fix: replicas should do expose blindly during rebuilding; server should not create orphan replicas for rebuilding lvols

---

pkg/spdk/engine.go

fix: improve logs and introduce minor fixes

---

pkg/spdk/engine.go

fix: improve engine validate logics

---

pkg/spdk/engine.go
pkg/spdk/replica.go

fix: port leakage caused by spdk client

---

pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/server.go

fix: fix engine replica deletion and replica varification issues

---

pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk_test.go

Issue longhorn/longhorn#9190
- fix(test): temporarily create spdk_tgt for each test case
- refactor: refactor the codes for closing spdk clients
- Refactor the codes for closing spdk clients
- Log error returned by the close function

refactor: refactor the codes for closing spdk clients

---

pkg/spdk/engine.go

chore: improve replica client close logic for engine ReplicaAdd 

---

pkg/spdk/engine.go

fix: make all replica maps in engine consistent

---

Dockerfile.dapper
pkg/spdk/disk.go
pkg/spdk/engine.go
pkg/spdk/replica.go
pkg/spdk/server.go

fix(dockerfile): resolve package dependency error

---

README.md

chore: update the outdated README.md

---

go.mod
go.sum
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go
vendor/modules.txt

chore(vendor): update dependencies

---

pkg/spdk/replica.go

This fixes a corner case: A replica has a correct head lvol but its caches get missed.
Now r.prepareHead() will create a head lvol if it is invalid or does not exists, then blindly update the caches.
Issue # https://github.com/longhorn/longhorn/issues/9942

fix: replica prepares a head with the caches correctly

---

pkg/spdk/engine.go

Issue Longhorn/longhorn#9965
An engine without a frontend is not exposed and without a NVMf subsystem, so no need to fail the engine in the
validateAndUpdateFrontend().

fix: engine without frontend should not be failed due to missing NVMf subsystem

---

Dockerfile.dapper

Issue https://github.com/longhorn/longhorn/issues/5573
Update SPDK commit ID to point at snapshot checksum.

fix(deps): update SPDK in Dockerfile

---

pkg/spdk/server.go

ref: https://github.com/longhorn/longhorn/issues/10075
Delete the existing backing image with unmatched UUID before creating

fix: delete the backing image with unmatched UUID before creating

---

pkg/spdk/backing_image.go
pkg/spdk/replica.go

Issue Longhorn/longhorn#9953
Race conditions
- https://github.com/longhorn/longhorn-spdk-engine/actions/runs/12510434157/job/34902067059
- https://github.com/longhorn/longhorn-spdk-engine/actions/runs/12511454363/job/34903777595?pr=289

fix(replica): fix race condition when operating backing image

---

pkg/spdk/engine.go

Issue https://github.com/longhorn/longhorn/issues/9488

fix: fix SIGSEGV: segmentation violation

---

scripts/test

This reverts commit 7081bdafab53a5d482b022d875993c80912aa632.
Somehow this fails unit tests in my dev machine. Need to do more investigation.

revert "fix(scripts): prevent different test suites from running concurrently

---

Dockerfile.dapper
pkg/spdk/engine.go

fix: prevent the flooding messages

---

pkg/spdk/replica.go

Issue longhorn/longhorn#10160
Delete the snapshot, if it exists, to allow the creation of a replacement snapshot during the restore operation.
`None`
`None`

fix: delete existing snapshot during restore operation

---

.github/workflows/build.yml

chore(workflow): update runners to longhorn-infra-oracle-<arch>-runners

---

.github/workflows/build.yml

This reverts commit 7b196817ae4af33e640c6ddd4e959628c5b9b88d.
Need to investigate and fix the hugepage issue first.
Issue #

chore: revert "chore(workflow): update runners to longhorn-infra-oracle-<arch>-runners"

---

pkg/spdk/util.go

fix: func connectNVMfBdev detaches the nvme controller before and after attachment (failure)

---

pkg/spdk/backing_image.go
pkg/spdk/replica.go

Issue https://github.com/longhorn/longhorn/issues/10340

fix: replica cannot put bi into chain during rebuilding

---

scripts/test

chore(test): mount hugetlbfs if it is missing

---

pkg/spdk/replica.go

Issue longhorn/longhorn#10335
so that the subsequent snapshot purge won't be blocked by checksum calculation.

fix: disable cksum calculation for system snapshots during and after rebuilding

---

pkg/client/client.go
pkg/spdk/server.go

https://github.com/longhorn/longhorn/issues/10472

feat: implement engine metrics collection and retrieval in server

---

pkg/spdk/backing_image.go

fix: fix log messages

---

scripts/test

test: increase test timeout to 120 minutes

---

pkg/spdk_test.go

test: increase spdk_tgt timeout to 120 minutes

---

pkg/spdk/engine.go
pkg/spdk_test.go

chore: add more log messages and increase the test timeout

---

scripts/test

test: increase timeout to 180 minutes

---

go.mod
go.sum
pkg/spdk/backing_image.go
pkg/spdk/backup.go
pkg/spdk/engine.go
pkg/spdk/engine_test.go
pkg/spdk/restore.go
pkg/spdk/server.go
pkg/spdk/util.go
pkg/types/types.go
vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/initiator.go
vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/nvme.go
vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/nvmecli.go
vendor/github.com/longhorn/go-spdk-helper/pkg/initiator/ublk_id_generator.go
vendor/github.com/longhorn/go-spdk-helper/pkg/jsonrpc/types.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/ublk.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/ublk.go
vendor/github.com/longhorn/go-spdk-helper/pkg/types/types.go
vendor/github.com/longhorn/go-spdk-helper/pkg/util/device.go
vendor/modules.txt

in-progress
longhorn/longhorn#9456

feat: implement ublk frontend for v2 data engine

---

pkg/spdk/replica.go

ref: https://github.com/longhorn/longhorn/issues/10527
`GetBdevLvolMapWithFilter(spdkClient, r.replicaLvolFilter)` will get the backing image as well,
**This is because, in some of the verify logic, we will need to get the backing image here to construct the chain with the backing image lvol, we can't only get the snapshot of the replica. The chain needs to include the backing image.**
```
func (r *Replica) replicaLvolFilter(bdev *spdktypes.BdevInfo) bool {
if bdev == nil || len(bdev.Aliases) < 1 || bdev.DriverSpecific.Lvol == nil {
return false
}
lvolName := spdktypes.GetLvolNameFromAlias(bdev.Aliases[0])
// it is okay to have backing image snapshot in the results, because we exclude it when finding root or construct the snapshot map
return IsReplicaLvol(r.Name, lvolName) || …
```

fix: dont delete backing image when rebuilding

---

Dockerfile.dapper
pkg/spdk/replica.go

fix: fix snapshot hash stop error checking

---

Dockerfile.dapper
Makefile

chore(Makefile): update SRC_BRANCH to master

---

go.mod
go.sum
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/client/basic.go
vendor/github.com/longhorn/go-spdk-helper/pkg/spdk/types/lvol.go
vendor/modules.txt

Issue https://github.com/longhorn/longhorn/issues/10799
This version of go-spdk-helper contains the new APIs for delta snapshot rebuilding.

chore(deps): update go-spdk-helper version

---

Dockerfile.dapper

chore(dockerfile): add more log

---

Dockerfile.dapper

fix(dockerfile): remove unnecessary sleep

---

pkg/spdk/engine.go

https://github.com/longhorn/longhorn/issues/11767
- Add size checking before restoration in  BackupRestore()
- Handle empty frontend in Expand()

fix(engine): handle empty frontend in Expand & size check in BackupRestore

---

pkg/spdk/replica.go
pkg/spdk/server.go

Longhorn 10112
Issue https://github.com/longhorn/longhorn/issues/10112

fix: avoid invalid state update during replica deletion

---

pkg/spdk/engine.go
pkg/spdk/replica.go

This helps with the snapshot/rebuilding-related issue debugging

fix: improve engine and replica logs
